export const projects = [
  {
    slug: 'efu-inventory',
    title: 'EFU IT Inventory',
    shortTitle: 'Inventory, made accountable.',
    year: '2026',
    status: 'Live',
    type: 'Enterprise Asset Management',
    summary: 'A role-based hardware inventory platform for assets, allocations, audits, dashboards and reporting.',
    description: 'Built during my software engineering internship to replace fragmented inventory workflows with one clear, controlled system for IT operations.',
    role: 'Full-stack developer',
    stack: ['React', 'TypeScript', 'ASP.NET Core', 'SQL Server', 'JWT'],
    liveUrl: 'https://efu-inventory-system-wji1.vercel.app/',
    sourceUrl: 'https://github.com/AijazAhmed001/EFU-IT-Inventory-System',
    accent: 'emerald',
    features: ['Role-based access for SuperAdmin, IT Admin and Viewer', 'Asset allocation history and auditable activity', 'Dashboard reporting and PDF exports', 'JWT authentication, rate limiting and API documentation'],
    challenge: 'Inventory data had to remain understandable and traceable while different roles performed different operations.',
    solution: 'I separated responsibilities across typed frontend features and backend services, then applied role checks, audit middleware and consistent resource models.',
    outcome: 'A deployable full-stack platform that demonstrates a complete enterprise workflow from interface to database.',
  },
  {
    slug: 'efu-ai',
    title: 'EFU AI Assistant',
    shortTitle: 'Answers grounded in business data.',
    year: '2026',
    status: 'In development',
    type: 'Enterprise AI Experience',
    summary: 'A context-aware assistant designed to turn business questions into verified answers, charts and tables.',
    description: 'An AI layer for the inventory experience that understands the active page, filters and user role before retrieving or presenting information.',
    role: 'Product and system designer',
    stack: ['React', 'FastAPI', 'RAG', 'WebSockets', 'SQL Server'],
    accent: 'violet',
    features: ['Page-aware and filter-aware context', 'Streaming answers with structured tables and charts', 'Role-aware retrieval and permission boundaries', 'Auditable prompts, queries and responses'],
    challenge: 'Fast answers are not useful unless they respect permissions and can be verified against business data.',
    solution: 'The architecture separates retrieval, permission checks, model orchestration and response rendering so each stage can be validated independently.',
    outcome: 'A production-oriented blueprint for adding conversational analytics without allowing the model unrestricted database access.',
  },
  {
    slug: 'nexus-hypercloud',
    title: 'NEXUS HyperCloud',
    shortTitle: 'Cloud infrastructure, designed as a product.',
    year: '2026',
    status: 'Architecture initiative',
    type: 'Multi-region Cloud Platform',
    summary: 'A cloud platform initiative spanning control planes, IAM, compute, networking, observability, SDKs and developer consoles.',
    description: 'NEXUS explores how a modern cloud platform can expose complex infrastructure through clear contracts, modular services and focused developer experiences.',
    role: 'Platform architect and developer',
    stack: ['.NET', 'React', 'Kubernetes', 'Kafka', 'PostgreSQL'],
    accent: 'cyan',
    features: ['Global, regional and cluster control planes', 'IAM, organizations, projects and policy services', 'Compute, networking, data and AI platform layers', 'Multi-language SDKs, CLI tooling and observability'],
    challenge: 'A cloud platform can become a collection of disconnected services unless ownership and contracts are explicit.',
    solution: 'The platform is organized around bounded domains, shared contracts, regional responsibility and consistent operational standards.',
    outcome: 'A comprehensive architecture and implementation roadmap for building a cloud platform incrementally without losing system coherence.',
  },
];

export function getProject(slug) {
  return projects.find(project => project.slug === slug);
}
