import { motion } from 'framer-motion';
import { ArrowRight, Download, Github, Linkedin, Mail, Sparkles, Code2, BrainCircuit, Database, ShieldCheck } from 'lucide-react';
import { useState } from 'react';
import Navbar from '../components/Navbar';
import SectionTitle from '../components/SectionTitle';
import Chatbot from '../components/Chatbot';
import { experience, projects, skills } from '../data/content';
const api=import.meta.env.VITE_API_URL || 'http://localhost:5000';
const reveal={initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.18},transition:{duration:.6}};
export default function Home(){const [status,setStatus]=useState('');const [form,setForm]=useState({name:'',email:'',subject:'',message:''});
 async function submit(e:React.FormEvent){e.preventDefault();setStatus('Sending...');try{const r=await fetch(`${api}/api/contact`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(!r.ok)throw new Error();setStatus('Message sent successfully.');setForm({name:'',email:'',subject:'',message:''});}catch{setStatus('Could not send. Make sure the backend is running.')}}
 return <div id="top"><Navbar/><main>
 <section className="hero"><div className="orb one"/><div className="orb two"/><motion.div className="hero-copy" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.8}}><div className="badge"><Sparkles/> Available for internships and opportunities</div><p className="kicker">FULL-STACK & AI DEVELOPER</p><h1>I build intelligent, secure and <span>beautiful digital products.</span></h1><p className="lead">I’m Aijaz Ahmed, a Computer Science student building enterprise AI assistants, full-stack systems, dashboards and database-driven applications.</p><div className="hero-actions"><a className="btn" href="#projects">Explore my work <ArrowRight/></a><a className="btn secondary" href="/resume.pdf" download><Download/> Download resume</a></div><div className="socials"><a href="https://github.com/AijazAhmed001" target="_blank"><Github/> GitHub</a><a href="#"><Linkedin/> LinkedIn</a><a href="mailto:your-email@example.com"><Mail/> Email</a></div></motion.div>
 <motion.div className="hero-visual" initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} transition={{delay:.2,duration:.8}}><div className="code-card"><div className="window"><i/><i/><i/></div><pre><code><span>const</span> developer = {'{'}\n  name: <b>"Aijaz Ahmed"</b>,\n  focus: [<b>"AI"</b>, <b>"Full Stack"</b>],\n  mission: <b>"Build useful products"</b>\n{'}'};</code></pre></div><div className="float-card top"><BrainCircuit/> AI Systems</div><div className="float-card bottom"><ShieldCheck/> Secure APIs</div></motion.div></section>
 <section className="tech-strip"><span>React</span><span>TypeScript</span><span>ASP.NET Core</span><span>ASP.NET Core</span><span>SQL Server</span><span>Docker</span></section>
 <motion.section id="about" className="section split" {...reveal}><div><SectionTitle eyebrow="ABOUT ME" title="Engineering ideas into real products"/><p className="large-copy">I combine software engineering, AI concepts and thoughtful UI design to create systems that are practical, maintainable and ready for real users.</p><p>I am studying BS Computer Science at Air University Karachi Campus and have worked on enterprise-focused projects during my EFU General Insurance internship.</p></div><div className="metrics"><div><strong>5+</strong><span>Featured projects</span></div><div><strong>15+</strong><span>Technologies</span></div><div><strong>2</strong><span>Leadership roles</span></div><div><strong>3.12</strong><span>First-semester CGPA</span></div></div></motion.section>
 <motion.section className="section" {...reveal}><SectionTitle eyebrow="WHAT I DO" title="Development from interface to intelligence" copy="Focused services that reflect the products I am learning to build professionally."/><div className="service-grid">{[[Code2,'Full-Stack Development','Responsive interfaces, APIs, authentication, databases and deployment.'],[BrainCircuit,'AI Assistants','Context-aware assistants, RAG concepts and safe business-data access.'],[Database,'Backend & Databases','FastAPI, ASP.NET Core, SQL systems, JWT and clean service architecture.'],[Sparkles,'UI/UX Engineering','Modern responsive dashboards, design systems and smooth interactions.']].map(([Icon,title,copy]:any)=><article className="service" key={title}><Icon/><h3>{title}</h3><p>{copy}</p></article>)}</div></motion.section>
 <motion.section id="skills" className="section" {...reveal}><SectionTitle eyebrow="SKILLS" title="Technology toolkit"/><div className="skills-grid">{Object.entries(skills).map(([group,list])=><article className="skill-card" key={group}><h3>{group}</h3><div className="tags">{list.map(x=><span key={x}>{x}</span>)}</div></article>)}</div></motion.section>
 <motion.section id="projects" className="section" {...reveal}><SectionTitle eyebrow="SELECTED WORK" title="Projects built around real problems" copy="Each card opens a detailed case-study page ready for your screenshots, architecture and results."/><div className="project-grid">{projects.map((p,i)=><motion.article className="project" key={p.id} whileHover={{y:-8}}><div className={`project-art art-${i%3}`}><span>{p.category}</span><h3>{p.title}</h3></div><div className="project-body"><p>{p.summary}</p><div className="tags">{p.stack.map(x=><span key={x}>{x}</span>)}</div><a href={`/projects/${p.id}`}>View case study <ArrowRight/></a></div></motion.article>)}</div></motion.section>
 <motion.section id="experience" className="section" {...reveal}><SectionTitle eyebrow="EXPERIENCE" title="Learning through ownership and leadership"/><div className="timeline">{experience.map((x,i)=><article key={x.role}><div className="dot">{i+1}</div><div><span>{x.period}</span><h3>{x.role}</h3><strong>{x.org}</strong><p>{x.details}</p></div></article>)}</div></motion.section>
 <motion.section className="section education" {...reveal}><SectionTitle eyebrow="EDUCATION" title="BS Computer Science"/><div className="education-card"><div><h3>Air University Karachi Campus</h3><p>Current undergraduate student focusing on programming, object-oriented development, digital logic, discrete structures, databases, AI systems and professional communication.</p></div><span>2025 — Present</span></div></motion.section>
 <motion.section id="contact" className="section contact" {...reveal}><div><SectionTitle eyebrow="LET’S CONNECT" title="Have a project or opportunity?"/><p className="large-copy">Send a message and it will appear inside the included admin dashboard.</p><div className="contact-note"><Mail/> your-email@example.com</div></div><form onSubmit={submit}><div className="two"><input required placeholder="Your name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="email" placeholder="Email address" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><input required placeholder="Subject" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/><textarea required rows={6} placeholder="Tell me about the opportunity or project" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/><button className="btn" type="submit">Send message <ArrowRight/></button><small>{status}</small></form></motion.section>
 </main><footer><a className="brand" href="#top">AA<span>.</span></a><p>Designed and developed by Aijaz Ahmed.</p><a href="/admin">Admin</a></footer><Chatbot/></div>}
