-- Additive Oracle migration. Safe only after reviewing the existing schema.
DECLARE
  l_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_exists FROM user_tables WHERE table_name = 'PermissionHistory';
  IF l_exists = 0 THEN
    EXECUTE IMMEDIATE q'~CREATE TABLE "PermissionHistory" (
      "Id" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      "UserId" RAW(16) NOT NULL, "PermissionId" RAW(16) NOT NULL,
      "PreviousValue" NUMBER(1) NOT NULL, "NewValue" NUMBER(1) NOT NULL,
      "ChangedByUserId" RAW(16) NOT NULL,
      "ChangedAt" TIMESTAMP(7) DEFAULT SYSTIMESTAMP NOT NULL,
      "CorrelationId" NVARCHAR2(100) NOT NULL,
      CONSTRAINT "PK_PermissionHistory" PRIMARY KEY ("Id"),
      CONSTRAINT "FK_PermissionHistory_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id"),
      CONSTRAINT "FK_PermissionHistory_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id"),
      CONSTRAINT "FK_PermissionHistory_Users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Users" ("Id")
    )~';
    EXECUTE IMMEDIATE 'CREATE INDEX "IX_PermissionHistory_UserId_ChangedAt" ON "PermissionHistory" ("UserId", "ChangedAt" DESC)';
  END IF;
END;
/
