import { Check, LogOut, Search, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { apiRequest, authHeaders } from '../services/api';
import type { AdminStats, ContactMessage } from '../types';
export default function Admin(){
 const [messages,setMessages]=useState<ContactMessage[]>([]),[stats,setStats]=useState<AdminStats|null>(null),[token,setToken]=useState(sessionStorage.getItem('portfolioToken')||''),[query,setQuery]=useState(''),[onlyUnread,setOnlyUnread]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({username:'',password:''});
 const load=useCallback(async()=>{try{const headers=authHeaders(token);const [m,s]=await Promise.all([apiRequest<ContactMessage[]>('/api/admin/messages',{headers}),apiRequest<AdminStats>('/api/admin/stats',{headers})]);setMessages(m);setStats(s);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load dashboard.');}},[token]);
 useEffect(()=>{if(token)load()},[token,load]);
 async function login(e:React.FormEvent){e.preventDefault();try{const d=await apiRequest<{token:string}>('/api/admin/login',{method:'POST',body:JSON.stringify(form)});sessionStorage.setItem('portfolioToken',d.token);setToken(d.token);setError('');}catch(e){setError(e instanceof Error?e.message:'Invalid credentials.')}}
 async function markRead(id:number){await apiRequest(`/api/admin/messages/${id}/read`,{method:'PATCH',headers:authHeaders(token)});load()}
 async function remove(id:number){if(!confirm('Delete this contact message?'))return;await apiRequest(`/api/admin/messages/${id}`,{method:'DELETE',headers:authHeaders(token)});load()}
 const shown=useMemo(()=>messages.filter(m=>(!onlyUnread||!m.read)&&`${m.name} ${m.email} ${m.subject} ${m.message}`.toLowerCase().includes(query.toLowerCase())),[messages,query,onlyUnread]);
 if(!token)return <main className="admin-login"><form className="panel" onSubmit={login}><span className="pill">SECURE AREA</span><h1>Portfolio Admin</h1><p>Sign in to review messages and analytics.</p><label>Username<input autoComplete="username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Password<input autoComplete="current-password" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><button className="btn" type="submit">Sign in</button>{error&&<small className="error">{error}</small>}</form></main>;
 return <main className="admin"><div className="admin-head"><div><span className="pill">ADMIN DASHBOARD</span><h1>Portfolio operations</h1></div><button className="btn secondary" onClick={()=>{sessionStorage.removeItem('portfolioToken');setToken('')}}><LogOut/> Logout</button></div>{error&&<p className="error-banner">{error}</p>}<div className="stats"><div><b>{stats?.totalMessages??0}</b><span>Total messages</span></div><div><b>{stats?.unreadMessages??0}</b><span>Unread</span></div><div><b>{stats?.projects??0}</b><span>Projects</span></div><div><b>{stats?.events??0}</b><span>Tracked events</span></div></div><div className="admin-toolbar"><div><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search messages..."/></div><label><input type="checkbox" checked={onlyUnread} onChange={e=>setOnlyUnread(e.target.checked)}/> Unread only</label></div><h2>Contact messages <small>({shown.length})</small></h2><div className="message-list">{shown.map(m=><article className={m.read?'':'unread'} key={m.id}><header><div><strong>{m.name} — {m.subject}</strong><small>{m.email} · {new Date(m.createdAtUtc).toLocaleString()}</small></div><div>{!m.read&&<button onClick={()=>markRead(m.id)} title="Mark read"><Check/></button>}<button onClick={()=>remove(m.id)} title="Delete"><Trash2/></button></div></header><p>{m.message}</p></article>)}{shown.length===0&&<div className="empty">No messages match your filters.</div>}</div></main>}
