import { motion } from 'framer-motion';
import { ArrowRight, BrainCircuit, Code2, Database, Download, Github, Linkedin, Mail, ShieldCheck, Sparkles } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import Chatbot from '../components/Chatbot';
import CommandPalette from '../components/CommandPalette';
import Navbar from '../components/Navbar';
import SectionTitle from '../components/SectionTitle';
import { experience, projects, skills } from '../data/content';
import { apiRequest } from '../services/api';
const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.15},transition:{duration:.55}};
const services=[
 {Icon:Code2,title:'Full-Stack Development',copy:'Responsive applications, secure APIs, authentication, data and deployment.'},
 {Icon:BrainCircuit,title:'AI Assistants',copy:'Context-aware assistants designed around authorized business data.'},
 {Icon:Database,title:'Backend & Databases',copy:'ASP.NET Core services, EF Core, SQL design and validated REST APIs.'},
 {Icon:Sparkles,title:'UI Engineering',copy:'Accessible dashboards, design systems and polished interactions.'}
];
export default function Home(){
 const [status,setStatus]=useState(''),[sending,setSending]=useState(false),[search,setSearch]=useState(false),[filter,setFilter]=useState('All');
 const [form,setForm]=useState({name:'',email:'',subject:'',message:''});
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearch(true)}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);
 const categories=['All',...new Set(projects.map(p=>p.category))];
 const visible=useMemo(()=>filter==='All'?projects:projects.filter(p=>p.category===filter),[filter]);
 async function submit(e:React.FormEvent){e.preventDefault();setSending(true);setStatus('');try{await apiRequest('/api/contact',{method:'POST',body:JSON.stringify(form)});setStatus('Thank you — your message was sent successfully.');setForm({name:'',email:'',subject:'',message:''});}catch(err){setStatus(err instanceof Error?err.message:'Could not send your message.');}finally{setSending(false)}}
 return <div id="top"><Navbar onSearch={()=>setSearch(true)}/><main>
 <section className="hero"><div className="orb one"/><div className="orb two"/><motion.div className="hero-copy" initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{duration:.7}}><div className="badge"><Sparkles/> Open to internships, remote roles and selected projects</div><p className="kicker">FULL-STACK & AI DEVELOPER</p><h1>I build secure systems with <span>useful intelligence.</span></h1><p className="lead">I’m Aijaz Ahmed, a Computer Science student building enterprise dashboards, ASP.NET Core APIs, database-driven applications and context-aware AI assistants.</p><div className="hero-actions"><a className="btn" href="#projects">Explore work <ArrowRight/></a><Link className="btn secondary" to="/recruiter">Recruiter view</Link><a className="btn ghost" href="/resume.pdf" download><Download/> Resume</a></div><div className="socials"><a href="https://github.com/AijazAhmed001" target="_blank" rel="noopener noreferrer"><Github/> GitHub</a><a href="https://www.linkedin.com/" target="_blank" rel="noopener noreferrer"><Linkedin/> LinkedIn</a><a href="mailto:aijaz@example.com"><Mail/> Email</a></div></motion.div>
 <motion.div className="hero-visual" initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} transition={{delay:.15,duration:.7}}><div className="code-card"><div className="window"><i/><i/><i/></div><pre><code><span>const</span> developer = {'{'}\n  name: <b>"Aijaz Ahmed"</b>,\n  builds: [<b>"Full Stack"</b>, <b>"AI"</b>],\n  values: [<b>"Security"</b>, <b>"Clarity"</b>]\n{'}'};</code></pre></div><div className="float-card top"><BrainCircuit/> AI Systems</div><div className="float-card bottom"><ShieldCheck/> Secure APIs</div></motion.div></section>
 <section className="tech-strip"><span>React</span><span>TypeScript</span><span>C#</span><span>ASP.NET Core</span><span>SQL Server</span><span>Docker</span></section>
 <motion.section id="about" className="section split" {...reveal}><div><SectionTitle eyebrow="ABOUT ME" title="Engineering ideas into useful products"/><p className="large-copy">I combine software engineering, data, AI concepts and thoughtful UI design to create systems that are practical, maintainable and easy to use.</p><p>I study BS Computer Science at Air University Karachi Campus and build enterprise-focused projects inspired by real operational problems.</p></div><div className="metrics"><div><strong>5</strong><span>Detailed projects</span></div><div><strong>20+</strong><span>Tools and technologies</span></div><div><strong>2</strong><span>Leadership roles</span></div><div><strong>Full stack</strong><span>Frontend to deployment</span></div></div></motion.section>
 <motion.section className="section" {...reveal}><SectionTitle eyebrow="WHAT I DO" title="From interface to intelligence"/><div className="service-grid">{services.map(({Icon,title,copy})=><article className="service" key={title}><Icon/><h3>{title}</h3><p>{copy}</p></article>)}</div></motion.section>
 <motion.section id="skills" className="section" {...reveal}><SectionTitle eyebrow="SKILLS" title="Technology toolkit with practical evidence"/><div className="skills-grid">{Object.entries(skills).map(([group,list])=><article className="skill-card" key={group}><h3>{group}</h3><div className="tags">{list.map(x=><span key={x}>{x}</span>)}</div></article>)}</div></motion.section>
 <motion.section id="projects" className="section" {...reveal}><SectionTitle eyebrow="SELECTED WORK" title="Projects built around real problems" copy="Explore architecture, challenges, solutions, features and technology decisions."/><div className="filters">{categories.map(c=><button className={filter===c?'active':''} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><div className="project-grid">{visible.map((p,i)=><motion.article className="project" key={p.id} whileHover={{y:-7}}><div className={`project-art art-${i%3}`}><span>{p.category}</span><h3>{p.title}</h3><small>{p.stack.slice(0,3).join(' · ')}</small></div><div className="project-body"><p>{p.summary}</p><div className="tags">{p.stack.slice(0,5).map(x=><span key={x}>{x}</span>)}</div><Link to={`/projects/${p.id}`}>View case study <ArrowRight/></Link></div></motion.article>)}</div></motion.section>
 <motion.section id="experience" className="section" {...reveal}><SectionTitle eyebrow="EXPERIENCE" title="Learning through ownership and leadership"/><div className="timeline">{experience.map((x,i)=><article key={x.role}><div className="dot">{i+1}</div><div><span>{x.period}</span><h3>{x.role}</h3><strong>{x.org}</strong><p>{x.details}</p></div></article>)}</div></motion.section>
 <motion.section className="section education" {...reveal}><SectionTitle eyebrow="EDUCATION" title="BS Computer Science"/><div className="education-card"><div><h3>Air University Karachi Campus</h3><p>Undergraduate study in programming, object-oriented development, digital logic, discrete structures, databases, management and professional communication.</p></div><span>2025 — Present</span></div></motion.section>
 <motion.section id="contact" className="section contact" {...reveal}><div><SectionTitle eyebrow="LET’S CONNECT" title="Have an opportunity or project?"/><p className="large-copy">Send a clear message about the role, project or collaboration. It will appear in the secure admin inbox.</p><div className="contact-note"><Mail/> aijaz@example.com</div></div><form onSubmit={submit}><div className="two"><label>Name<input required autoComplete="name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input required type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label></div><label>Subject<input required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Message<textarea required minLength={10} rows={6} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label><button className="btn" type="submit" disabled={sending}>{sending?'Sending…':'Send message'} <ArrowRight/></button><small className="form-status" aria-live="polite">{status}</small></form></motion.section>
 </main><footer><Link className="brand" to="/">AA<span>.</span></Link><p>Designed and developed by Aijaz Ahmed.</p><div><Link to="/recruiter">Recruiter</Link><Link to="/admin">Admin</Link></div></footer><Chatbot/><CommandPalette open={search} onClose={()=>setSearch(false)}/></div>;
}
